common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

myproject/myproject/urls.py
# """
# URL configuration for myproject project.

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/5.1/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import path
# from my_app import views  # my_app으로 수정


# urlpatterns = [
#     path('', views.box_office, name='box_office'),  # 빈 경로에 대해 box_office 뷰를 호출
#     path('box_office/', views.box_office, name='box_office'),
# ]

from django.contrib import admin
from django.urls import path
from my_app import views  # my_app으로 수정
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('box_office/',views.box_office, name='box_office'),  # 루트 경로에 대해서 box_office 뷰를 호출
    path('trending_tv/', views.trending_tv_shows, name='trending_tv_shows'),
    path('common/', include('common.urls')), #로그인
    
]

myproject/urls.py
# """
# URL configuration for myproject project.

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/5.1/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import path
# from my_app import views  # my_app으로 수정


# urlpatterns = [
#     path('', views.box_office, name='box_office'),  # 빈 경로에 대해 box_office 뷰를 호출
#     path('box_office/', views.box_office, name='box_office'),
# ]

from django.contrib import admin
from django.urls import path
from my_app import views  # my_app으로 수정
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('box_office/',views.box_office, name='box_office'),  # 루트 경로에 대해서 box_office 뷰를 호출
    path('trending_tv/', views.trending_tv_shows, name='trending_tv_shows'),
    path('common/', include('common.urls')), #로그인
    
    
]

my_app/models.py
from django.db import models
from datetime import datetime




# 배우 모델
class Actor(models.Model):
    name = models.CharField(max_length=255)  # 배우 이름
    birth_date = models.DateField(null=True, blank=True)  # 생년월일 (선택 사항)

    def __str__(self):
        return self.name

# 영화 모델
class Movie(models.Model):
    movie_cd = models.CharField(max_length=20, unique=True)
    movie_nm = models.CharField(max_length=255)
    open_dt = models.CharField(max_length=10, null=True, blank=True)
    genre = models.CharField(max_length=255, null=True, blank=True)
    director = models.CharField(max_length=255, null=True, blank=True)
    poster_url = models.URLField(null=True, blank=True)
    box_office_sales = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    box_office_rank = models.IntegerField(null=True, blank=True)
    rank = models.IntegerField()  # 순위
    audi_cnt = models.IntegerField(default=0)  # 당일 관객수
    audi_acc = models.IntegerField(default=0)  # 누적 관객수

    def __str__(self):
        return self.movie_nm

class TVShow(models.Model):
    title = models.CharField(max_length=200)
    overview = models.TextField()
    release_date = models.DateField(null=True, blank=True)
    poster_url = models.URLField(null=True, blank=True)
    vote_average = models.FloatField()
    popularity = models.FloatField()

    def __str__(self):
        return self.title

my_app/views.py
# Create your views here.
from django.shortcuts import render
import requests
from django.http import JsonResponse
from bs4 import BeautifulSoup
from my_app.models import Movie, TVShow
from datetime import datetime, timedelta


def trending_tv_shows(request):
    api_key = 'bf5c5094ad11fd8f27152d30f1980757'
    url = f"https://api.themoviedb.org/3/trending/tv/week?api_key={api_key}&language=ko-KR"
    
    # 어제 날짜로 설정
    yesterday = (datetime.today() - timedelta(days=1)).strftime('%Y%m%d')

    # API 요청 파라미터
    params = {
        'key': api_key,
        'targetDt': yesterday,  # 날짜를 동적으로 변경
    }

    # TMDb API에서 트렌딩 TV 시리즈 정보 가져오기
    try:
        response = requests.get(url, params=params)
        response.raise_for_status()
        trending_tv_data = response.json().get('results', [])
    except requests.exceptions.RequestException as e:
        trending_tv_data = []
        print(f"API 요청 실패: {e}")
    
    # 데이터베이스에서 TV 시리즈 정보를 가져옵니다.
    tv_shows = TVShow.objects.all().order_by('popularity')

    # 포스터 이미지 URL 앞에 붙일 기본 URL
    image_base_url = 'https://image.tmdb.org/t/p/w500'
    
    # 트렌딩 TV 시리즈에 포스터 URL 추가하기
    for show in trending_tv_data:
        if show.get('poster_path'):
            show['poster_url'] = image_base_url + show['poster_path']
        else:
            show['poster_url'] = None  # 포스터가 없는 경우 처리

    # 템플릿으로 데이터 전달
    return render(request, 'my_app/trending_tv.html', {'tv_shows': trending_tv_data, 'database_tv_shows': tv_shows})
# def movie_reservation(request):
#     # CGV 웹사이트에서 예매율 정보를 크롤링
#     url = 'http://www.cgv.co.kr/movies/?lt=1&ft=0'
#     response = requests.get(url)

#     if response.status_code == 200:
#         soup = BeautifulSoup(response.text, 'html.parser')
#         movies = soup.find_all('div', class_='sect-movie-chart')

#         movie_list = []
#         for movie in movies:
#             # 'strong' 태그가 없으면 'title'을 빈 문자열로 설정
#             title_tag = movie.find('strong')
#             title = title_tag.text if title_tag else '제목 없음'

#             # 예매율을 찾을 때 None인지 확인
#             reservation_rate_tag = movie.find('span', class_='txt-grade')
#             reservation_rate = reservation_rate_tag.text if reservation_rate_tag else '정보 없음'  # 예매율이 없으면 '정보 없음' 표시
            
#             movie_list.append({'title': title, 'reservation_rate': reservation_rate})

#         # 크롤링한 데이터 템플릿에 전달
#         return render(request, 'my_app/box_office.html', {'movie_list': movie_list})

#     return render(request, 'my_app/box_office.html', {'error': '데이터를 가져오는 데 실패했습니다.'})

def box_office(request):
    # KOFIC API로 일일 박스오피스 데이터 가져오기
    api_key = '04c52266e1fdcfe2b96d62445a151a99'
    yesterday = (datetime.today() - timedelta(days=1)).strftime('%Y%m%d')  # 어제 날짜로 설정

    url = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json'
    params = {
        'key': api_key,
        'targetDt': yesterday,  # 날짜를 동적으로 변경
    }

    response = requests.get(url, params=params)

    if response.status_code == 200:
        # 박스오피스 데이터를 가져옵니다.
        box_office_data = response.json().get('boxOfficeResult', {}).get('dailyBoxOfficeList', [])
    else:
        box_office_data = []
    
    # 데이터베이스에서 영화 정보를 가져옵니다.
    movies = Movie.objects.all().order_by('rank')
    
    reservation_url = 'http://www.cgv.co.kr/movies/?lt=1&ft=0'
    reservation_response = requests.get(reservation_url)

    if reservation_response.status_code == 200:
        soup = BeautifulSoup(reservation_response.text, 'html.parser')

        # 영화 제목과 예매율 정보를 제대로 찾기 위한 수정
        movies = soup.find_all('div', class_='box-contents')  # 해당하는 div로 수정
        
        movie_list = []
        for movie in movies:
            # 영화 제목을 찾음
            title_tag = movie.find('strong')  # 영화 제목을 포함한 태그를 찾음
            title = title_tag.text.strip() if title_tag else '정보 없음'
            
            # 예매율을 찾음
            reservation_rate_tag = movie.find('strong', class_='percent')
            if reservation_rate_tag:
                reservation_rate = reservation_rate_tag.find('span').text.strip()
            else:
                reservation_rate = '정보 없음'

            movie_list.append({'title': title, 'reservation_rate': reservation_rate})
    else:
        movie_list = []


    return render(request, 'my_app/box_office.html', {
        'box_office_data': box_office_data,
        'movies': movies,
        'movie_list': movie_list
    })

myproject/my_app/views.py
# Create your views here.
from django.shortcuts import render
import requests
from django.http import JsonResponse

def box_office(request):
    api_key = '04c52266e1fdcfe2b96d62445a151a99'
    url = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json'
    params = {
        'key': api_key,
        'targetDt': '20241201',  # 날짜를 동적으로 변경할 수 있습니다.
    }

    response = requests.get(url, params=params)

    if response.status_code == 200:
        data = response.json()['boxOfficeResult']['dailyBoxOfficeList']
    else:
        data = []

    return render(request, 'my_app/box_office.html', {'data': data})


def trending_tv_shows(request):
    api_key = 'bf5c5094ad11fd8f27152d30f1980757'
    if not api_key:
        return JsonResponse({'error': 'API 키가 설정되지 않았습니다.'}, status=500)

    # 파라미터 준비
    user_id = '21272571'  # 사용자 ID
    target_date = '20241201'  # 특정 날짜 설정
    url = f"https://api.themoviedb.org/3/trending/tv/week?api_key={api_key}&language=ko-KR"
    
    response = requests.get(url)
    data = response.json()
        
    return render(request, 'my_app/trending_tv.html',{'tv_shows': data['results']})

my_app/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}기본 타이틀{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <!-- 네비게이션바 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">웹사이트 이름</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/box_office/">홈</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/box_office/">영화</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/trending_tv/">드라마</a>
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                        {% else %}
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                        {% endif %}
                    </li>
                    <li>
                        {% if not user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/mypage/">마이페이지</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- 페이지 콘텐츠 -->
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS 추가 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

my_app/templates/form_error.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}